
type Mutation {
    saveUser(userApp:UserAppInput):UserApp
    initUser(userApp:UserAppInput):UserApp

    saveIssue(issue:IssueInput) :Issue
    updateIssue(issue:IssueInput) : Issue
    saveValue(value:ValueInput):[CustomFieldValue]
    addComment(comment:CommentInput):[Comment]
    saveConfigWithQG(configEntry:ConfigEntryInput):[ConfigEntry]
    createProjectOrSave(project:ProjectInput):Project
    saveIssueType(issueType:IssueTypeInput):IssueType
    affectIssueTypeForParent(childId:Int,parrentId:Int):IssueType
    removeIssueTypeParent(childId:Int):IssueType
    saveWorkFlow(workFlow:WorkFlowInput):WorkFlow
    affectWorkFlow(issueType:IssueTypeInput):WorkFlow
    addStatus(status:StatusInput, workFlow:WorkFlowInput):WorkFlow
    saveCustomField(customField:CustomFieldImput):CustomField
    useCustomField(usingCustomField:UsingCustomFieldInput):[UsingCustomField]
    unUseCustomField(usingCustomField:UsingCustomFieldInput):[UsingCustomField],
    assigneToUser(issue:IssueInput,executor:String):Issue
    saveOrUpdateConfig(configProject:ConfigProjectInput):ConfigProject
    addUserInGroupe(username:String,groupeId:Int,roles:[String]):MemberGroupe
    deleteMember(memberId:Int):ResponseApp
    saveEvent(event:EventInput):Event
    deleteEvent(eventId:Int):Event
    addDocument(document:DocumentInput):Document
    saveUploaded(uploaded:UploadedInput):Uploaded
    saveCustomFilter(customFilter:IssueFilterInput):IssueFilter
    saveLabel(label:LabelInput):Label
    addLabelInIssue(issueId:Int,labelId:Int):IssueLabels
    removeLabelInIssue(issueId:Int,labelId:Int):IssueLabels
    deleteIssue(issueId:Int):ResponseApp
    createCanal(canall:CanallInput):Canall
    sendMessage(newMessage:MessageAppInput):MessageApp
    forwardDocument(document:DocumentInput):Document
    deleteDocumentById(documentId:Int) :ResponseApp
    seenNotification(userId:String):ResponseApp
}


