type Query {
    getUser(username: String!): UserApp,
    allUsers : [UserApp],
    allIssue :[Issue]
    findIssueById(id:Int) :[Issue]
    findIssueByUserId(id:String):[Issue]
    findAllStatus:[Status]
    allComment(issueId:Int):[Comment]
    allFiles(issueId:Int):[File]
    allCustomFieldByIssue(issueId:Int):[CustomField]
    getCustomField(id:Int):CustomField
    getValues(issueId:Int):[CustomFieldValue]
    getIssueTypeById(issueTypeId:Int):IssueType
    loadDirectory(issueId:Int):Repertoire
    loadGroupeMember(userId:String):[MemberGroupe]
    getConfig(typeEntry:String):[ConfigEntry]
    allConfig:[ConfigEntry]
    allProjects:[Project]

    getWorkFlow(workFlowId:Int):WorkFlow
    allWorkFlow:[WorkFlow]
    workFlowsByProject(projectId:Int):[WorkFlow]

    getProject(prefix:String):Project
    getConfigProject(projectId:Int):[ConfigProject]
    getIssueType(issueTypeId:Int):IssueType
    allIssueType(projectId:Int):[IssueType]
    issueByCriteria(criterias:[CriteriaInput]):[Issue]
    allCustomField(projectId:Int):[CustomField]
    customFieldsByIssueType(issueTypeId:Int):[UsingCustomField]
    getGroupeUserForProject(prefix:String):[GroupeUser]
    listIssueTypeMaster(projectId:Int):[IssueType]
    listIssueTypeSubtasks(masterId:Int):[IssueType]
    getNextKey(issueTypeId:Int):String
    getIssue(issueKey:String):Issue
    loadSubtask(parentId:Int):[Issue]
    loadIssueMasterByProject(projectId:Int):[Issue]
    searchIssues(criteria:IssueSearchCriteriaInput):[Issue]
    allEventType:[EventType]
    searchEvents(criteria:EventSearchCriteriaInput):[Event]
    getByEventId(eventId:Int):Event
    getProjectByUser(userId:String):[Project]
    loadPermissiontTask:Permission
    getDocuments(issueId:Int,typeDocument:String):[Document]
    loadDocumentById(documentId:Int):Document
    listActivity:[DomainActivity]
    getMyFilters(projectId:Int,userId:String):[IssueFilter]
    getLabelByProject(projectId:Int):[Label]
    getIssueById(issueId:Int):Issue
    getSettings(userId:String):[AppSettings]
    getCanalByProject(projectId:Int,userIds:[String]):[Canall]
    getNotificationsByUserId(userId:String):[Notification]

}
