
# R2DBC
#spring.r2dbc.url=r2dbc:mysql://localhost:3306/follow-task
#spring.r2dbc.username=test1
#spring.r2dbc.password=q5+UtF-Y


server.port=8881

master-db.url=jdbc:mysql://kinga-db:3306/best_follow_task
master-db.username=follow-task-user
master-db.password=kinGa15687
master-db.dialect=org.hibernate.dialect.MySQLDialect
master-db.driver=com.mysql.cj.jdbc.Driver
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

