
# R2DBC
#spring.r2dbc.url=r2dbc:mysql://localhost:3306/follow-task
#spring.r2dbc.username=test1
#spring.r2dbc.password=q5+UtF-Y

master-db.url=jdbc:mysql://localhost:3306/follow-task
master-db.username=root
master-db.password=q5+UtF-Y
master-db.dialect=org.hibernate.dialect.MySQLDialect
master-db.driver=com.mysql.cj.jdbc.Driver

