server.port = 8081
spring.servlet.multipart.max-file-size=2000MB
spring.servlet.multipart.max-request-size=2000MB
spring.jpa.properties.hibernate.format_sql=true
logging.file.name=logs/follow-task.log

# R2DBC
#spring.r2dbc.url=jdbc:h2:file://${user.home}/.taskManager/profile/data/database
#spring.r2dbc.username=test1
#spring.r2dbc.password=q5+UtF-Y

master-db.url=jdbc:h2:file:${user.home}/.kinga-data/follow-task-2025-01-23
master-db.deriver=org.h2.Driver
master-db.username=test1
master-db.password=q5+UtF-Y
master-db.driver = org.h2.Driver
master-db.dialect = org.hibernate.dialect.H2Dialect
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
