spring.graphql.graphiql.enabled: true
master-db.url=jdbc:h2:file:${user.home}/.kinga-data/follow-task-2025-01-23
master-db.deriver=org.h2.Driver
master-db.username=test1
master-db.password=q5+UtF-Y
master-db.driver = org.h2.Driver
master-db.dialect = org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
server.port = 8081
spring.servlet.multipart.max-file-size=2000MB
spring.servlet.multipart.max-request-size=2000MB

# R2DBC
spring.r2dbc.url=r2dbc:h2:file://${user.home}/.kinga-data/follow-task-2025-01-23
spring.r2dbc.username=test1
spring.r2dbc.password=q5+UtF-Y
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

